# Generated by Django 4.2.3 on 2023-09-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
